# Generated by Django 2.2 on 2024-02-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0007_auto_20240212_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
